version: "3.6"
services:
  database:
    image: sipekmichal/bikeomysqldb:5.7
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bikeo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - /tmp/logs/bikeodb:/var/log/mysql
    restart: always
  webserver:
    image: sipekmichal/bikeoapp:latest
    depends_on:
       - database
    links: 
       - database
    build: 
      context: ./appserver
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - /tmp/logs/bikeoapp:/usr/local/tomcat/logs
    restart: always
