version: "3.6"
services:
  database:
    image: bikeodb
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bikeo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always
  webserver:
    image: bikeoapp
    depends_on:
       - database
    links: 
       - database
    build: 
      context: ./appserver
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./logs:/usr/local/tomcat/logs
    restart: always
