version: "3.3"

services:

  database:
    build:
      context: ./database
    image: bikeodb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bikeo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306" 
    volumes:
      - ./data:/var/lib/mysql
  
  webserver:
    build: 
      context: ./appserver
    image: bikeoapp
    ports:
      - "8080:8080" 
      - "8000:8000"
