version: "3.3"

services:

  database:
    build:
      context: ./database
    image: bikeodb
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "3306:3306" 

  webserver:
    build: 
      context: ./appserver
    image: bikeoapp
    ports:
      - "8080:8080" 
      - "8000:8000"
